import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "./components/MySessionProvider";
import NavBar from "./components/NavBar";
//import { authOptions } from "./api/auth/[...nextauth]/route";
import { authOptions } from "./authOptions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bigfoot Reporting Collective",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[url('/background.jpg')]`}
      >
        <SessionProvider session={session}>
          <NavBar /> {children}
        </SessionProvider>
      </body>
    </html>
  );
}
